[package]
name = "offline_transaction"
authors = { workspace = true }
version = "0.1.0"
edition = "2024"

[dependencies]
bitcoin = { version = "0.32", features = ["rand"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
hex = "0.4"
thiserror = "2"
colored = "3"
